name: CICD

on:
  push:
    branches:
      # Only run workflow on release/v1.0, v15.3 or v7.09 branch
      - 'release/v[0-9]+.[0-9]+'

jobs:
  success_build:
    # Check if the commit message contains #norun and if it does, skip the workflow and if CONDITION is set 'SUCCESS' it will run the workflow otherwise skip the workflow
    if: ${{startsWith(github.event.head_commit.message, '#NORUN') == false }}
    runs-on: ubuntu-latest
    steps:
    # Check out the code
    - name: Check out the code
      uses: actions/checkout@v3

   # Scan for Vulnerabilities with Trivy
    - name: Scan for Vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        severity: 'CRITICAL'

 # Get the requirements to build the image
    - name: Set up QEMU
      id: docker
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    # Login to docker
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}         
        password: ${{ secrets.DOCKERHUB_PASSWORD }}