name: CICD

on:
  push:
    branches:
      - 'release/v[0-9]+.[0-9]+'  # Trigger the workflow for specific version branches.

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}  # Set Slack webhook URL as a global environment variable.

jobs:
  build_and_scan:
    if: startsWith(github.event.head_commit.message, '#NORUN') == false  # Condition to skip workflow if commit message starts with '#NORUN'.
    runs-on: ubuntu-latest  # Specifies the runner that the job will execute on.
    steps:
    - name: Check out the code
      uses: actions/checkout@v3  # Uses the checkout action to fetch the repository code.

    - name: Scan for Vulnerabilities
      uses: aquasecurity/trivy-action@master  # Uses Trivy to scan the codebase for vulnerabilities.
      with:
        scan-type: 'fs'  # Set the scan type to filesystem.
        severity: ${{ job.status == 'success' && 'CRITICAL' || 'HIGH' }}  # Adjust severity based on job status.
        ignore-unfixed: ${{ job.status != 'success' }}  # Ignore unfixed issues if previous job failed.
        format: 'table'  # Output the scan results in table format.
        output: 'trivy-results.txt'  # Specify the output file for scan results.

    - name: Set up QEMU and Docker Buildx
      uses: docker/setup-buildx-action@v3  # Sets up Docker Buildx for multi-architecture docker builds.

    - name: Login to Docker Hub
      uses: docker/login-action@v3  # Logs into Docker Hub using the provided credentials.
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5  # Builds and pushes the Docker image to Docker Hub.
      with:
        push: true
        tags: kaungkaungpro/cicd_docker:${{ github.sha }}  # Tag the image with the commit SHA.
      id: build-and-push

    - name: Install cosign
      uses: sigstore/cosign-installer@v2.2.0  # Installs Cosign for signing Docker images.
      with:
        cosign-release: 'v2.2.4'  # Specifies the version of Cosign to use.

    - name: Sign image with a key
      run: cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${{ env.TAGS }}@${{ env.DIGEST }}"  # Signs the built Docker image using Cosign.
      env:
        TAGS: kaungkaungpro/cicd_docker:${{ github.sha }}
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        DIGEST: ${{ steps.build-and-push.outputs.digest }}

    - name: Notify Slack on Build and Scan Status
      uses: rtCamp/action-slack-notify@v2  # Sends a notification to Slack using the rtCamp action.
      with:
        title: ${{ job.status == 'success' && 'Image build and signed' || 'Scan failed - Kyaw Lin Thu' }}
        message: |
          Name: Kyaw Lin Thu
          Matriculation: A0290864U
          Email: e1327895@u.nus.edu
          GitHub: https://github.com/KaungKaungPro/Assignment.git
          Docker: https://hub.docker.com/repository/docker/kaungkaungpro/cicd_docker/general
        color: ${{ job.status == 'success' && '#36A64F' || '#FF0000' }}  # Sets message color based on job status.
