name: CICD

on:
  push:
    branches:
      # Only run workflow on release/v1.0, v15.3 or v7.09 branch
      - 'release/v[0-9]+.[0-9]+'

jobs:
  success_build:
    # Check if the commit message contains #norun and if it does, skip the workflow and if CONDITION is set 'SUCCESS' it will run the workflow otherwise skip the workflow
    if: ${{ vars.CONDITION == 'SUCCESS' && startsWith(github.event.head_commit.message, '#NORUN') == false }}
    runs-on: ubuntu-latest
    steps:
    # Check out the code
    - name: Check out the code
      uses: actions/checkout@v3

    # Scan for Vulnerabilities with Trivy
    - name: Scan for Vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        severity: 'CRITICAL'

    # Get the requirements to build the image
    - name: Set up QEMU
      id: docker
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    # Login to docker
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}         
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Build and push the image
    - name: Build and push
      uses: docker/build-push-action@v5
      id: build-and-push
      with:
        push: true
        tags: kaungkaungpro/cicd_docker:${{ github.sha }}

    # Install Cosign
    - name: Install cosign
      uses: sigstore/cosign-installer@2.2.0
      with:
        cosign-release: 'v2.2.4'

    # Sign image with a key
    - name: Sign image with a key
      run: |
        cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${TAGS}@${DIGEST}"
      env:
        TAGS: kaungkaungpro/cicd_docker:${{ github.sha }}
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        DIGEST: ${{ steps.build-and-push.outputs.digest }}